SET NOCOUNT ON;
CREATE TABLE #TBX_JsonConstructor_Input(Ordinal int,ValueKind nvarchar(max),[Value] nvarchar(max));
INSERT #TBX_JsonConstructor_Input VALUES(1,N'string',N'synthetic');
BEGIN TRY EXEC toolbelt_json.USP_JsonArray @EntriesTable=N'#TBX_JsonConstructor_Input'; THROW 54600,N'Uppercase reserved prefix accepted.',63; END TRY BEGIN CATCH IF ERROR_NUMBER()<>53601 THROW; END CATCH;
IF (SELECT COUNT(*) FROM #TBX_JsonConstructor_Input)<>1 THROW 54600,N'Reserved caller table changed.',64;
BEGIN TRY EXEC toolbelt_json.USP_JsonObject @EntriesTable=N'#TBX_JsonConstructor_Input'; THROW 54600,N'Object uppercase reserved prefix accepted.',66; END TRY BEGIN CATCH IF ERROR_NUMBER()<>53601 THROW; END CATCH;
DECLARE @Help TABLE(HelpContractVersion varchar(16),SchemaName sysname NULL,ObjectName sysname NULL,Section varchar(32),Ordinal int,ItemName sysname NULL,SqlDataType varchar(256),IsRequired bit,IsNullable bit,DefaultValue nvarchar(4000),Description nvarchar(max),ExampleSql nvarchar(max));
INSERT @Help EXEC toolbelt_json.USP_JsonArray @EntriesTable=N'#TBX_JsonConstructor_Input',@MaxEntries=0,@Hilfe=1;
IF NOT EXISTS(SELECT 1 FROM @Help WHERE Section='DESCRIPTION') THROW 54600,N'Reserved fixture prevented Help.',67;
DROP TABLE #TBX_JsonConstructor_Input;
CREATE TABLE #CaseInput(Ordinal int,[Key] nvarchar(max),ValueKind nvarchar(max),[Value] nvarchar(max));
INSERT #CaseInput VALUES(1,N'a',N'string',N'first'),(3,N'A',N'string',N'second'),(9,N'a ',N'null',NULL);
CREATE TABLE #CaseOutput(Dummy int);
EXEC toolbelt_json.USP_JsonObject @EntriesTable=N'#CaseInput',@ResultTable=N'#CaseOutput';
DECLARE @Actual nvarchar(max);
EXEC sys.sp_executesql N'SELECT @x=JsonValue FROM #CaseOutput',N'@x nvarchar(max) OUTPUT',@Actual OUTPUT;
IF @Actual IS NULL OR CONVERT(varbinary(max),@Actual)<>CONVERT(varbinary(max),N'{"a":"first","A":"second","a ":null}') THROW 54600,N'Case-sensitive context binary keys changed.',65;
CREATE TABLE #TBX_JsonConstructor_Fragments(ConflictingSchema int);
BEGIN TRY EXEC toolbelt_json.USP_JsonArray @EntriesTable=N'#CaseInput'; THROW 54600,N'Unrelated reserved temp eclipsed core.',68; END TRY BEGIN CATCH IF ERROR_NUMBER()<>53601 THROW; END CATCH;
DROP TABLE #TBX_JsonConstructor_Fragments;
